# Generated by Django 4.2.4 on 2023-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('name', models.TextField(blank=True, verbose_name='Имя пользователя')),
                ('username', models.TextField(blank=True, null=True, verbose_name='Ник пользователя')),
                ('phone', models.TextField(unique=True)),
                ('company', models.TextField(verbose_name='Компания')),
                ('prof', models.TextField(verbose_name='Должность')),
                ('speaker', models.TextField(verbose_name='Спикер')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('meet_dt', models.DateTimeField(verbose_name='Дата и время встречи')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
    ]
