# Generated by Django 4.2.4 on 2023-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.TextField(null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='meet_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата и время встречи'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='prof',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='users',
            name='speaker',
            field=models.TextField(null=True, verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='users',
            name='theme',
            field=models.TextField(null=True, verbose_name='Тема'),
        ),
    ]
