# Generated by Django 4.2.4 on 2023-08-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0005_slots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'verbose_name': 'слот', 'verbose_name_plural': 'слоты'},
        ),
        migrations.AlterModelTable(
            name='slots',
            table='slots',
        ),
    ]
